services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  redis-data:
    