---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app-deployment
  namespace: devops
spec:
  selector:
    matchLabels:
      app: redis-app
  replicas: 2
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
        - name: devops-app
          image: devops/app:latest
          env:
            - name: REDIS_HOST
              value: redis-server
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: devops-service
  namespace: devops
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: tcp
  selector:
    app: redis-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-app-ingress
  namespace: devops
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: "www.192.168.56.9.sslip.io"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: devops-service
              port:
                number: 3000
